# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 00:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('matricula', models.IntegerField(db_index=True, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('integrantes', models.ManyToManyField(related_name='integrantes', to='subscriber.Alumno')),
                ('lider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lider', to='subscriber.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('materia', models.CharField(choices=[('IHC', 'Interaccion Humano Computadora'), ('DM', 'Dispositivos Moviles'), ('CI', 'Computo Integrado')], max_length=5)),
                ('mesa', models.CharField(max_length=3)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.Evento')),
            ],
        ),
    ]
