# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='credentials',
            new_name='usuario',
        ),
    ]
