# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0004_auto_20160329_0312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projecto',
            new_name='Proyecto',
        ),
    ]
