# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0005_auto_20160330_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='proyecto',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='subscriber.Proyecto'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='materia',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='materia',
            field=models.ManyToManyField(to='subscriber.Materia'),
        ),
    ]
