# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0006_auto_20160404_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='mesa',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
