# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 00:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0007_auto_20160411_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider', to='subscriber.Alumno'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
