# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0008_auto_20160413_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='apellidos',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='maestro',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
