# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0010_auto_20160428_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='evento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='evento',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.Maestro'),
        ),
    ]
