# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0011_auto_20160503_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='maestro',
        ),
        migrations.AddField(
            model_name='maestro',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriber.Materia'),
        ),
    ]
