# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0012_auto_20160503_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='evento',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 3, 8, 2, 59, 105823, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 3, 8, 3, 5, 266050, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
    ]
