# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 04:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriber', '0014_auto_20160505_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
