# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0015_alumno_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='maestro',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
