# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0016_auto_20160505_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.Proyecto'),
        ),
    ]
