# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0017_auto_20160505_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estatus',
            field=models.IntegerField(default=1),
        ),
    ]
